# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='img/', width_field='width_field'),
        ),
    ]
