# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20170122_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
