# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='heading',
            field=models.CharField(default='heading', max_length=140),
        ),
    ]
