# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='heading',
            field=models.CharField(max_length=140),
        ),
    ]
