# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160930_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
